### ISSUE TITLE
OSError: [WinError 10042] An unknown, invalid, or unsupported option or level was specified in a getsockopt or setsockopt call

### ISSUE THREAD

**Issue by seLain** [seLain/mattermost_bot#19]
Environment: 
 * Python 3.6.4
 * Websocket 0.47.0

```
Traceback (most recent call last):
  File "mm_bot.py", line 19, in <module>
    bot.run()
  File "C:\py36_venv\MissAchieve\lib\site-packages\mattermost_bot\bot.py", line
36, in run
    self._dispatcher.loop()
  File "C:\py36_venv\MissAchieve\lib\site-packages\mattermost_bot\dispatcher.py"
, line 120, in loop
    'user_added', 'user_removed']):
  File "C:\py36_venv\MissAchieve\lib\site-packages\mattermost_bot\mattermost.py"
, line 196, in messages
    if not self.connect_websocket():
  File "C:\py36_venv\MissAchieve\lib\site-packages\mattermost_bot\mattermost.py"
, line 183, in connect_websocket
    self._connect_websocket(url, cookie_name='MMAUTHTOKEN')
  File "C:\py36_venv\MissAchieve\lib\site-packages\mattermost_bot\mattermost.py"
, line 192, in _connect_websocket
    else ssl.CERT_NONE
  File "C:\py36_venv\MissAchieve\lib\site-packages\websocket\_core.py", line 494
, in create_connection
    websock.connect(url, **options)
  File "C:\py36_venv\MissAchieve\lib\site-packages\websocket\_core.py", line 217
, in connect
    options.pop('socket', None))
  File "C:\py36_venv\MissAchieve\lib\site-packages\websocket\_http.py", line 70,
 in connect
    sock = _open_socket(addrinfo_list, options.sockopt, options.timeout)
  File "C:\py36_venv\MissAchieve\lib\site-packages\websocket\_http.py", line 110
, in _open_socket
    sock.setsockopt(*opts)
```

Possibly caused by a [known bug in Python 3.6.4](https://bugs.python.org/issue32394), according to websocket-client/websocket-client#370

**Comment by seLain** [comment]
Seems ok if upgrading Python from 3.6.4 to 3.6.5rc1
